<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/functions.php';
require_login();
$alerts=db_read('alerts');$users=db_read('users');$devices=db_read('devices');$services=db_read('services');
$id=(string)($_GET['id']??'');$idx=db_find_index($alerts,$id);if($idx===null){header('Location: alerts.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){$alerts[$idx]['status']=trim((string)($_POST['status']??$alerts[$idx]['status']));$alerts[$idx]['operator_comment']=trim((string)($_POST['operator_comment']??$alerts[$idx]['operator_comment']));$alerts[$idx]['service']=trim((string)($_POST['service']??$alerts[$idx]['service']));db_write('alerts',$alerts);header('Location: alert-view.php?id='.urlencode($id));exit;}
if(isset($_GET['run_ai'])&&$_GET['run_ai']==='1'){$ai=ai_classify((string)($alerts[$idx]['voice_text']??''));$alerts[$idx]['ai_result']=$ai['ai_result'];$alerts[$idx]['urgency']=$ai['urgency'];$alerts[$idx]['confidence']=$ai['confidence'];$alerts[$idx]['service']=$ai['service'];$alerts[$idx]['ai_recommendation']=$ai['recommendation'];db_write('alerts',$alerts);header('Location: alert-view.php?id='.urlencode($id));exit;}
$alert=$alerts[$idx];$userName=find_name_by_id($users,(string)($alert['user_id']??''),'id','full_name');$deviceName=find_name_by_id($devices,(string)($alert['device_id']??''),'device_id','device_name');
$pageTitle='Alert tafsiloti';$currentPage='alerts.php';include __DIR__.'/includes/header.php';include __DIR__.'/includes/sidebar.php';
?>
<main class="main-wrap"><?php include __DIR__.'/includes/navbar.php'; ?>
<section class="grid cols-3">
<article class="card"><h3 style="margin-top:0;">Asosiy ma’lumot</h3><p><strong>Alert ID:</strong> <?= h($alert['alert_id']??'-') ?></p><p><strong>Vaqt:</strong> <?= h($alert['created_at']??'-') ?></p><p><strong>Foydalanuvchi:</strong> <?= h($userName) ?></p><p><strong>Qurilma:</strong> <?= h($deviceName) ?></p><p><strong>Status:</strong> <span class="<?= badge_class($alert['status']??'Yangi') ?>"><?= h($alert['status']??'-') ?></span></p><p><strong>Aniq koordinata:</strong> <?= h((string)($alert['latitude']??'')) ?>, <?= h((string)($alert['longitude']??'')) ?></p><p><strong>Lokatsiya:</strong> <a class="btn secondary" target="_blank" href="https://maps.google.com/?q=<?= urlencode((string)$alert['latitude']) ?>,<?= urlencode((string)$alert['longitude']) ?>">Google Map</a></p><div class="map-embed"><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=<?= urlencode((string)$alert['latitude']) ?>,<?= urlencode((string)$alert['longitude']) ?>&z=16&output=embed"></iframe></div></article>
<article class="card"><h3 style="margin-top:0;">AI tahlil</h3><p><strong>Voice text:</strong> <?= h($alert['voice_text']??'-') ?></p><p><strong>AI natija:</strong> <?= h($alert['ai_result']??'-') ?></p><p><strong>Urgency:</strong> <?= h($alert['urgency']??'-') ?></p><p><strong>Confidence:</strong> <?= h((string)($alert['confidence']??'-')) ?></p><p><strong>Tavsiya:</strong> <?= h($alert['ai_recommendation']??'Operator tomonidan tekshiruv tavsiya etiladi.') ?></p><a class="btn warn" href="alert-view.php?id=<?= urlencode($id) ?>&run_ai=1">AI qayta classify</a></article>
<article class="card"><h3 style="margin-top:0;">Service route</h3><p><strong>Tanlangan xizmat:</strong> <?= h($alert['service']??'-') ?></p><?php if(!empty($alert['service_hotline'])): ?><p><strong>Hotline:</strong> <?= h((string)$alert['service_hotline']) ?></p><?php endif; ?><?php if(!empty($alert['route_note'])): ?><p><strong>Route note:</strong> <?= h((string)$alert['route_note']) ?></p><?php endif; ?><div class="mini-list"><?php foreach($services as $srv): ?><div class="mini-item"><div><strong><?= h($srv['name']??'-') ?></strong><small><?= h($srv['hotline']??'-') ?> · SLA <?= h((string)($srv['sla_minutes']??'-')) ?> min</small></div></div><?php endforeach; ?></div></article>
</section>
<section class="card"><h3 style="margin-top:0;">Operator boshqaruvi</h3><form method="post" class="form-grid"><div><label class="muted">Status</label><select name="status"><?php foreach(statuses() as $st): ?><option value="<?= h($st) ?>" <?= ($alert['status']??'')===$st?'selected':'' ?>><?= h($st) ?></option><?php endforeach; ?></select></div><div><label class="muted">Service</label><select name="service"><?php foreach($services as $srv): $name=(string)($srv['name']??''); ?><option value="<?= h($name) ?>" <?= ($alert['service']??'')===$name?'selected':'' ?>><?= h($name) ?></option><?php endforeach; ?></select></div><div class="full"><label class="muted">Operator izohi</label><textarea name="operator_comment"><?= h((string)($alert['operator_comment']??'')) ?></textarea></div><div class="full"><button class="btn success" type="submit">Yangilash</button> <a class="btn secondary" href="alerts.php">Ro‘yxatga qaytish</a></div></form></section>
</main><?php include __DIR__.'/includes/footer.php'; ?>
